export const SIGN_IN_MODAL_OPEN = "SIGN_IN_MODAL_OPEN";
export const SIGN_IN_MODAL_CLOSE = "SIGN_IN_MODAL_CLOSE";
export const SIGN_UP_MODAL_OPEN = "SIGN_UP_MODAL_OPEN";
export const SIGN_UP_MODAL_CLOSE = "SIGN_UP_MODAL_CLOSE";
